name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Bundling
      run: |
        gem install bundler -v 2.2.3
        bundle install

    - name: Linting
      run: bin/rubocop

    - name: Testing
      run: COVER=1 bin/rspec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
